### ISSUE TITLE
Support Ruby 2.2

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-analytics-api-ruby#12]
```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]

$ bundle exec rake
/Users/dentarg/.rubies/ruby-2.2.0/bin/ruby -S rspec ./spec/client_spec.rb ./spec/parser_spec.rb ./spec/post_spec.rb ./spec/query_spec.rb ./spec/result_spec.rb -fs -c
/Users/dentarg/.gem/ruby/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
	from /Users/dentarg/.gem/ruby/2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/crack-0.4.2/lib/crack/json.rb:6:in `require'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/crack-0.4.2/lib/crack/json.rb:6:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/crack-0.4.2/lib/crack.rb:6:in `require'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/crack-0.4.2/lib/crack.rb:6:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/webmock-1.18.0/lib/webmock.rb:5:in `require'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/webmock-1.18.0/lib/webmock.rb:5:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/library_hooks/webmock.rb:3:in `require'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/library_hooks/webmock.rb:3:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/configuration.rb:503:in `require'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/configuration.rb:503:in `load_library_hook'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/configuration.rb:68:in `block in hook_into'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/configuration.rb:68:in `each'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr/configuration.rb:68:in `hook_into'
	from /Users/dentarg/twingly/ruby/twingly-analytics-api-ruby/spec/vcr_setup.rb:5:in `block in <top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/vcr-2.9.2/lib/vcr.rb:199:in `configure'
	from /Users/dentarg/twingly/ruby/twingly-analytics-api-ruby/spec/vcr_setup.rb:3:in `<top (required)>'
	from /Users/dentarg/twingly/ruby/twingly-analytics-api-ruby/spec/query_spec.rb:2:in `require'
	from /Users/dentarg/twingly/ruby/twingly-analytics-api-ruby/spec/query_spec.rb:2:in `<top (required)>'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/configuration.rb:1065:in `load'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/configuration.rb:1065:in `each'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/command_line.rb:18:in `run'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/runner.rb:89:in `run'
	from /Users/dentarg/.gem/ruby/2.2.0/gems/rspec-core-2.99.0/lib/rspec/core/runner.rb:17:in `block in autorun'
/Users/dentarg/.rubies/ruby-2.2.0/bin/ruby -S rspec ./spec/client_spec.rb ./spec/parser_spec.rb ./spec/post_spec.rb ./spec/query_spec.rb ./spec/result_spec.rb -fs -c failed
```

**Comment by dentarg** [comment]
Oops, my bad. The `Gemfile.lock` I had was installing/using `safe_yaml 1.0.3`, when I removed it, `safe_yaml 1.0.4` was installed/used, and the tests now passes.

(Thanks to Google for finding https://github.com/dtao/safe_yaml/issues/73#issuecomment-68539659 for me.)
